#!/bin/bash
#$ -cwd
#$ -j y
#$ -l h_rt=1:0:0
#$ -l h_vmem=8G
#$ -pe smp 8
#$ -t 1-33
#$ -o logs/

ix=$SGE_TASK_ID
sample=$(sed -n -e "$SGE_TASK_ID p" /data/Blizard-Rakyan/Fran/pilots/novogene_2020_05_22/WGBS/src/samples.txt)

ifd="/data/Blizard-Rakyan/Fran/pilots/novogene_2020_05_22/WGBS/data/fq/${sample}"
ofd="result/${sample}"

mkdir -p $ofd

module load fastqc
fastqc -o $ofd -t $NSLOTS ${ifd}/*.fq.gz 
