#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=3:0:0
#$ -l h_vmem=4G
#$ -t 1-10
#$ -w w
#$ -o logs/

samples=($(ls -d /data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/mRNAseq/data/trimmed/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}
sample=$(basename $path)

echo "${sample}: Started"

ofd="/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/mRNAseq/data/star/${sample}"
gfd="/data/Blizard-Rakyan/Rakyan_Lab_Files/Genomes/Mouse/WG/MM10/rDNA/WG_rDNA/STAR/"

rm -rf $ofd && mkdir -p $ofd && cd $ofd

ifd="${rfd}${sample}"

R1=`find "/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/mRNAseq/data/trimmed/${sample}" | grep "_1.fq.gz$"`
R2=`find "/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/mRNAseq/data/trimmed/${sample}" | grep "_2.fq.gz$"`

R=$(basename $R1 _1_val_1.fq.qz)

module load -s pigz
module load -s samtools
module load -s star/2.7.0f

STAR --outSAMstrandField intronMotif \
    --quantMode GeneCounts \
    --outSAMtype BAM SortedByCoordinate \
    --readFilesCommand zcat \
    --genomeDir ${gfd} \
    --readFilesIn $R1 $R2 \
    --outFileNamePrefix "${R}_" \
    --runThreadN ${NSLOTS}

echo "${sample}: Finished"
