#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=240:0:0
#$ -l h_vmem=8G
#$ -t 1-24
#$ -tc 10
#$ -w w
#$ -l highmem
#$ -o logs/

samples=($(ls -d /data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/bismark_nd/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}
sample=$(basename $path)

echo "${sample}: Started"

ofd="/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/bismark_nd/${sample}"
cd $ofd

ls *.bai  >/dev/null 2>&1 && 
    echo "${sample}: Previously indexed" &&
    exit

fn=$(ls | grep "pe.bam")
ofn="${fn}.sorted"

echo "${sample}: Sorting"
module load -s samtools
( samtools sort -o ${ofn} -@ $NSLOTS $fn &&
    mv $ofn $fn &&
    echo "${sample}: Sorted" &&
    samtools index $fn &&
    echo "${sample}: Indexed" &&
    echo "${sample}: Finished" ) ||
    echo "${sample}: Error"
