#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=2G
#$ -t 1-24
#$ -w w
#$ -o logs/

samples=($(ls -d /data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/bamtobed_rdna/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}
sample=$(basename $path)

echo "${sample}: Started"

module load gcc R/4.0.2

Rscript --vanilla MEF_mspI_dist.R $sample

echo "Finished"
