#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 4
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G
#$ -t 1-22
#$ -w w
#$ -o logs/

samples=($(ls -d /data/Blizard-Rakyan/Robert/Data/Human_Mandinka/Real_Data/RRBS/Cell_ConStress/data/bam_wg/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}
sample=$(basename $path)

echo "${sample}: Started"

mfn="/data/Blizard-Rakyan/Rakyan_Lab_Files/Genome_Annotations/Human/WG/RepeatMasker/hg38.rmsk.bed"

ofd="/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/Human/bam_mask/${sample}"
mkdir -p $ofd && cd $ofd
ofn="${sample}.bam"

ifd="/data/Blizard-Rakyan/Robert/Data/Human_Mandinka/Real_Data/RRBS/Cell_ConStress/data/bam_wg/${sample}/"
ifn=$(ls ${ifd}*.bam)

module load bedtools/2.28.0

bedtools intersect -a $ifn -b $mfn -v  > ${sample}.bam

echo "${sample}: Finished"
