#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=1:0:0
#$ -l h_vmem=8G
#$ -t 1-96
#$ -w w
#$ -o logs/

samples=($(ls -d ../../data/bam_mask/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}
sample=$(basename $path)

echo "${sample}: Started"

ofn="${sample}.bed"

ofd="../../data/bamtobed/${sample}/"

mkdir -p $ofd

module load bedtools/2.28.0

ifn=$( realpath ../../data/bam_mask/${sample}/${sample}.bam )
bedtools bamtobed -i ${ifn} > ${ofd}${ofn}


echo "${sample}: Finished"
