#!/bin/bash
#$ -cwd
#$ -j y
#$ -l h_rt=1:0:0
#$ -l h_vmem=8G
#$ -pe smp 4
#$ -t 2-33
#$ -o logs/

samples=($(ls -d ../../data/bismark/*/))
ix=$(( $SGE_TASK_ID-1 ))


mkdir -p ../../data/covs_rdna/

path=${samples[$ix]}

sample=`basename $path`
echo "${sample}: Started"

module load -s samtools

samtools depth -d 0 -r "BK000964.3_looped_3008" ${path}/*pe.bam > \
    ../../data/covs_rdna/${sample}.cov && \
    echo "${sample}: Finished successfully"
