#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=8G
#$ -t 1-33
#$ -o logs/

samples=($(ls -d /data/Blizard-Rakyan/Selin/projects/mouse_strains/WGBS/data/bam_rdna/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}
sample=$(basename $path)

module load qualimap

echo "${sample}: Started"

ifd="/data/Blizard-Rakyan/Selin/projects/mouse_strains/WGBS/data/bam_rdna/${sample}"

qualimap bamqc -bam ${ifd}/*.bam

echo "${sample}: Finished"
