#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=8G
#$ -t 1-96
#$ -w w
#$ -o logs/

idx=$SGE_TASK_ID
sample=$(awk "NR==${idx} {print;exit}" ../../src/samples.txt)

echo "${sample}: Started"

low="125"
high="135"

module load -s samtools/1.10

echo "${sample}: Whole Genome"

ifd="../../data/bismark/${sample}/"
ofd="../../data/bismark_${low}_${high}/${sample}/"
mkdir -p $ofd

samtools view -h ${ifd}*.bam | \
      awk -v l=$low -v h=$high 'substr($0,1,1)=="@" || ($9>=l && $9<=h) || ($9<=-l && $9>=-h)' | \
        samtools view -b > ${ofd}${sample}.bam

echo "${sample}: rDNA"

ifd="../../data/bam_rdna/${sample}/"
ofd="../../data/bam_rdna_${low}_${high}/${sample}/"
mkdir -p $ofd

samtools view -h ${ifd}*.bam | \
      awk -v l=$low -v h=$high 'substr($0,1,1)=="@" || ($9>=l && $9<=h) || ($9<=-l && $9>=-h)' | \
        samtools view -b > ${ofd}${sample}.bam

echo "${sample}: Finished"
