#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=240:0:0
#$ -l h_vmem=4G
#$ -t 1-24
#$ -tc 10
#$ -w w
#$ -o logs/

samples=($(ls -d /data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/trimmed_nd/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}
sample=$(basename $path)

echo "${sample}: Started"

ofd="/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/bismark_nd/${sample}"
gfd="/data/Blizard-Rakyan/Rakyan_Lab_Files/Genomes/Mouse/WG/MM10/rDNA/WG_rDNA/"

rm -rf $ofd
mkdir -p $ofd && cd $ofd

ifd="${rfd}${sample}"

R1=`find "/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/trimmed_nd/${sample}"| grep "_1.fq.gz$"`
R2=`find "/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/trimmed_nd/${sample}"| grep "_2.fq.gz$"`

module load -s pigz
module load -s samtools
module load -s bismark

REPCORES=$((NSLOTS / 2))

bismark \
--genome /data/Blizard-Rakyan/Rakyan_Lab_Files/Genomes/Mouse/WG/MM10/rDNA/WG_rDNA/ \
-1 $R1 \
-2 $R2 \
-p ${REPCORES} \
--gzip \
--non_directional \
--unmapped

echo "${sample}: Finished"
