#!/bin/bash
#$ -cwd
#$ -j y
#$ -l h_rt=1:0:0
#$ -l h_vmem=4G
#$ -pe smp 8
#$ -t 1-24
#$ -o logs/

samples=($(ls -d /data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/bismark_nd/*/))
ix=$(( $SGE_TASK_ID-1 ))
path=${samples[$ix]}

sample=`basename $path`
region="BK000964.3_looped_3008"

echo "${sample}: Started"

module load -s samtools/1.10 bcftools/1.10.2

ofd="/data/Blizard-Rakyan/Selin/projects/MEF_SD_DEC/RRBS/Data_Novogene/X204SC22010869-Z01-F001/bam_rdna_nd/${sample}/"
mkdir -p $ofd

bams=$(ls ${path}*pe.bam)

obam=${ofd}${sample}.bam

samtools merge -R ${region} -@ $NSLOTS $obam $bams
samtools index ${obam}

echo "${sample}: Finished"
